### ISSUE TITLE
模型释放问题

### ISSUE THREAD

**Issue by shining-love** [Rex-LK/tensorrt_learning#4]
rex佬，我看了rex佬你这个ncnn的多线程，我想请问你这个没有看到哪里可以释放模型的地方？是不是缺少一个函数去释放模型和资源？

**Comment by Rex-LK** [comment]
对,把我这边把fast_det_ 修改成 shared_ptr了

**Comment by shining-love** [comment]
> 对,把我这边把fast_det_ 修改成 shared_ptr了

rex佬，我想在外面封装。一般封装你也知道，有模型初始化，模型推理，模型释放。我对于模型和结果释放这个不知道，你这个生产这消费者模型的，怎么在开一个外部模型和结果释放函数可以去手动随时自己控制释放与否的

**Comment by Rex-LK** [comment]
如果完全不进行封装的话
模型加载用 这两个api就可以了， 
 net_.load_param(param_path.c_str());
 net_.load_model(model_path.c_str());
模型推理使用
ncnn::Extractor ex = net_.create_extractor();
ex.set_num_threads(num_threads);
ex.input(inputName.c_str(), input_);
ex.extract(outputName.c_str(), output_);

模型释放的话，原本是离开作用域自动释放的，如果要手动释放，可以调用 
net_.clear()

**Comment by shining-love** [comment]
> 如果完全不进行封装的话 模型加载用 这两个api就可以了， net_.load_param(param_path.c_str()); net_.load_model(model_path.c_str()); 模型推理使用 ncnn::Extractor ex = net_.create_extractor(); ex.set_num_threads(num_threads); ex.input(inputName.c_str(), input_); ex.extract(outputName.c_str(), output_);
> 
> 模型释放的话，原本是离开作用域自动释放的，如果要手动释放，可以调用 net_.clear()

好的rex佬，那我研究一下。谢谢

**Comment by shining-love** [comment]
> > 如果完全不进行封装的话 模型加载用 这两个api就可以了， net_.load_param(param_path.c_str()); net_.load_model(model_path.c_str()); 模型推理使用 ncnn::Extractor ex = net_.create_extractor(); ex.set_num_threads(num_threads); ex.input(inputName.c_str(), input_); ex.extract(outputName.c_str(), output_);
> > 模型释放的话，原本是离开作用域自动释放的，如果要手动释放，可以调用 net_.clear()
> 
> 好的rex佬，那我研究一下。谢谢
rex佬你看看，你的代码是不是有点问题

![image](https://github.com/Rex-LK/tensorrt_learning/assets/49702076/a11dd434-90af-496a-92bf-75a5cb4ba5ca)
![image](https://github.com/Rex-LK/tensorrt_learning/assets/49702076/fc0eccd1-ab39-44bb-8c30-33e6dd17d209)
![image](https://github.com/Rex-LK/tensorrt_learning/assets/49702076/75131890-5bce-415f-9977-c643b850bcd5)

**Comment by shining-love** [comment]
这个变成了指针的智能指针了？

**Comment by Rex-LK** [comment]
出现问题了吗

**Comment by shining-love** [comment]
> 出现问题了吗

是的。我现在把那句修改了：
![image](https://github.com/Rex-LK/tensorrt_learning/assets/49702076/756937ec-443e-4d39-a7f0-31b43f1924b7)

**Comment by Rex-LK** [comment]
可以的
